<a href="https://colab.research.google.com/github/Peshniwah1/AI_Modelling_MUK/blob/main/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from math import * # import math / import math as m

In [ ]:
pi


3.141592653589793

In [ ]:
# Numerical Python
import numpy as np
# Array ( This is similar to a list, just that for it, it must have the same datatype) # Creating one dimension array
a = np.array([1,4,5,6], int) # np.array([#,#,#,#], datatype)
print(a)



[1 4 5 6]


In [ ]:
# Creating Multi dimension array
b	= np.array([[1,4,5,6],[7,8,9,10]], int) # np.array([[#,#,#,#],[#,#,#,#]] datatype)
print(b)


[[ 1  4  5  6]
 [ 7  8  9 10]]


In [ ]:
#Shape of the array
b.shape

(2, 4)

In [ ]:
# Reshaping the array
b.reshape((4,2)) # reshape((#,#))

array([[ 1,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# Transpose function
b.  transpose()


array([[ 1,  7],
       [ 4,  8],
       [ 5,  9],
       [ 6, 10]])

In [ ]:
# Array Mathematics

x = np.array([1,2,3], int)
y = np.array([4,5,6], int)

#Addition
z = x + y
z


array([5, 7, 9])

In [ ]:
# Array iteration in x
x = np.array([1,2,3], int)
for i in x:
   print(i)



1
2
3


In [ ]:
# Array Items summation
x.sum()

6

In [ ]:
# Array Items Product
x. prod( )


6

In [ ]:
# Importing Pandas Library
import pandas as pd

#create a list
a =  [1, 2,3,4]
print(a)


[1, 2, 3, 4]


In [ ]:
# Create a Dataframe
dataframe = pd.Series(a)
print(dataframe)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
#Creating your own index
dataframe = pd.Series(a, index=['w', 'x', 'y', 'z'])
print(dataframe)


w    1
x    2
y    3
z    4
dtype: int64


In [ ]:
data = {
"Calories" : [429, 380, 390],
"Duration" : [50,40,30]
}
df = pd.DataFrame(data, index=["Day1", "Day2", "Day3"])
print(df)


      Calories  Duration
Day1       429        50
Day2       380        40
Day3       390        30


In [ ]:
print(df.loc["Day2"])

Calories    380
Duration     40
Name: Day2, dtype: int64


In [ ]:
# Locating a row using indexes

data =	{
"Calories" : [429, 380, 390],
"Duration" : [50,40,30]
       }
df = pd.DataFrame(data)
print(df.loc[1])

Calories    380
Duration     40
Name: 1, dtype: int64


In [ ]:
# Importing csv file using Panda
import pandas as pd

df =  pd.read_csv("test_standard_bank.csv")




FileNotFoundError: ignored